version: "3.9"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "20000:20000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
  dynamoInit:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    ports:
     - "8123:8123"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region us-west-2
  cribbageServer:
    image: cribbage
    depends_on:
      - dynamoInit
    environment:
      deploy: docker
    ports:
      - "8080:8080"
  # cribbage:
  #   depends_on:
  #     - cribbageServer