version: "3.9"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "18079:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
  dynamoInit:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region us-west-2
  cribbageServer:
    image: cribbage
    depends_on:
      - dynamoInit
      - mysql
    environment:
      deploy: dockercompose
      CRIBBAGE_DSN_HOST: mysql
      CRIBBAGE_DSN_USER: root
      CRIBBAGE_DSN_PASSWORD: letmein
      CRIBBAGE_DSN_PARAMS: "parseTime=true&timeout=90s&writeTimeout=90s&readTimeout=90s&tls=skip-verify&maxAllowedPacket=1000000000&rejectReadOnly=true"
      CRIBBAGE_restPort: 8088
      CRIBBAGE_MYSQL_CREATE_TABLES: "true"
    ports:
      - "18080:8088"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: cribbage
    command: ['mysqld', '--skip-character-set-client-handshake', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  # cribbage:
  #   depends_on:
  #     - cribbageServer