version: "3.9"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "18079:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
  dynamoInit:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    command:
      dynamodb create-table --endpoint-url http://dynamodb-local:8000 --billing-mode PAY_PER_REQUEST --region us-west-2 --table-name cribbage --attribute-definitions AttributeName=cribbageID,AttributeType=S AttributeName=spec,AttributeType=S --key-schema AttributeName=cribbageID,KeyType=HASH AttributeName=spec,KeyType=Range
  mysql-database:
    image: mysql:8
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: balrog
      MYSQL_USER: gandalf
      MYSQL_PASSWORD: flyyoufools
      MYSQL_DATABASE: cribbage
    command: ['mysqld', '--skip-character-set-client-handshake', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_as_cs']
    healthcheck:
      test: "mysql -P13306 -ugandalf -pflyyoufools  -Dcribbage -e 'SHOW TABLES;'"
      timeout: 20s
      retries: 10
  cribbage-server:
    image: joshprzybyszewski/cribbage:latest
    depends_on:
      dynamoInit:
        condition: service_started
      mysql-database:
        condition: service_healthy
    volumes:
      - ./server/persistence/dynamo/.dockerComposeAWS:/home/.aws
    environment:
      deploy: dockercompose
      CRIBBAGE_DB: dynamodb
      CRIBBAGE_DBURI: http://dynamodb-local:8000
      HOME: "/home" # for aws config
      CRIBBAGE_DSN_HOST: mysql-database
      CRIBBAGE_DSN_USER: gandalf
      CRIBBAGE_DSN_PASSWORD: flyyoufools
      CRIBBAGE_DSN_PARAMS: "parseTime=true&timeout=90s&writeTimeout=90s&readTimeout=90s&tls=skip-verify&maxAllowedPacket=1000000000&rejectReadOnly=true"
      CRIBBAGE_restPort: 8088
      CRIBBAGE_MYSQL_CREATE_TABLES: "true"
      CRIBBAGE_MYSQL_CREATE_ERROR_IS_OK: "true"
    ports:
      - "18080:8080"