name: build-client
defaults:
  run:
    working-directory: ./app/client
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "13"
      - name: Install node modules
        run: npm install
      - name: Lint client
        run: npm run lint
      - name: Build client
        run: npm run build
