name: react-tests
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    paths:
    - client/
    - **.js
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: yarn
    - name: Yarn Build
      run: yarn build
    - name: Yarn Test
      run: yarn test --watchAll=false